### PR TITLE
use ament export targets

### LINKED ISSUE #751: Consider updating to ament_export_targets (Modern CMake)
# Current Behavior

BehaviorTree.CPP  has support for ament (YAY!), but it's using the old-style macros that were for before CMake 3, in that they set variables. 

# Desired Behavior

When you call `find_package` in the ROS ecosystem, it's becoming more common practice to use `target_link_libraries` and link to an exported namespaced target. This is not yet possible.

* Update [this section of ament_build.cmake](https://github.com/BehaviorTree/BehaviorTree.CPP/blob/a5525fa88f2425247da226d881a89394780bdc5d/cmake/ament_build.cmake#L21-L37) to :
  * Remove the line with `ament_export_include_directories`
  * Remove the line with `ament_export_libraries`
  * Add a call to `ament_export_targets`
* Update documentation on recommended usage with `target_link_libraries` as an alternative to `ament_target_dependencies`, perhaps by appending a "Usage with CMake" Guide somewhere to the docs
* Add a CI task that verifies the changes to the ROS build don't break consumers
* Patch this into a release, and release binaries for rolling, iron and humble, since it is backwards compatible

# Outside help

I can do all the work

# Reference

https://docs.ros.org/en/humble/How-To-Guides/Ament-CMake-Documentation.html#installing

### PR DESCRIPTION
**Pull request by Ryanf55**
# Purpose

Upgrade the support to latest ament recommendations, which uses CMake targets.

# Addtions

I added a CI task to check it works. The stuff in `export` folder is merely to check the installation of BTCPP is correct.

# Ticket

Closes #751 

# CI status

CI will be red until the next `humble` sync.

### CODE REVIEW

**Comment by facontidavide** [comment]
Red CI....

**Comment by Ryanf55** [comment]
> Red CI....

Yes, Ill get it green after `sync`. For now, I'll put this in draft. 

If you want some of the CI stuff merged in a separate MR that can go in now, I'm happy split it up.

**Comment by facontidavide** [comment]
closing this, unti it passes CI checks

**Comment by Ryanf55** [comment]
Do you have ability to re-run CI on this? It should work now.

**Pull request closed without merging**
