### PR TITLE
Add support to concat strings and numbers in scripting

### PR DESCRIPTION
**Pull request by bochen87**
Solves #766

### CODE REVIEW

**Comment by facontidavide** [comment]
The potential issue I see with this is that there are two contraddicting use case:

1. Someone may want to concatenate string with numbers, so for instance

```
"path_" + 4 -> "path_4"
```

2. Someone may want strings to be interpreted as numbers
```
"3" + 4 -> 7
```

What would be probably "wrong" is:
```
"3" + 4 -> "37"
```
So, the only sane way to do this, in my opinion is including functions `to_number()` and `to_string()`:

```
"path" + to_string(4) -> "path_4"
to_number("3") + 4 -> 37
```
This is considerably more work, but the only way to avoid technical debt from being created, in my opinion.

**Comment by bochen87** [comment]
> The potential issue I see with this is that there are two contraddicting use case:
> 
> 1. Someone may want to concatenate string with numbers, so for instance
> 
> ```
> "path_" + 4 -> "path_4"
> ```
> 
> 2. Someone may want strings to be interpreted as numbers
> 
> ```
> "3" + 4 -> 7
> ```
> 
> What would be probably "wrong" is:
> 
> ```
> "3" + 4 -> "37"
> ```
> 
> So, the only sane way to do this, in my opinion is including functions `to_number()` and `to_string()`:
> 
> ```
> "path" + to_string(4) -> "path_4"
> to_number("3") + 4 -> 37
> ```
> 
> This is considerably more work, but the only way to avoid technical debt from being created, in my opinion.

It would be nice, but I guess quite a large amount of work to make it work properly, as this approach also has some pitfalls, i.e. "3,14" vs "3.14" vs "8'000". However, in the meantime, this could still be a good enough intermediate solution as it does at least allow for the usecase 1 to be solved.

**Comment by facontidavide** [comment]
> However, in the meantime, this could still be a good enough intermediate solution as it does at least allow for the usecase 1 to be solved.

Sorry, not adding this feature yet. I can't afford to have side effects that haven't been considered carefully

**Comment by seanng-1** [comment]
Would a better solution for this be: to add a new operator specifically for string concatenation? Similar to how it is done in Lua.
e.g.
```
value := 10
message := "The value is " .. value
```
would result in `The value is 10`

I can see this avoiding any issues with people wanting to use strings converted to numbers as it is explicitly for string concatenation.

**Comment by facontidavide** [comment]
closing in favor of https://github.com/BehaviorTree/BehaviorTree.CPP/pull/802

**Pull request closed without merging**
