### PR TITLE
Fix dependency in package.xml

### PR DESCRIPTION
**Pull request by wep21**

### CODE REVIEW

**Comment by facontidavide** [comment]
what problem does this fix?

**Comment by wep21** [comment]
dependency for .so library installed via apt
```
❯ ldd /opt/ros/galactic/lib/libbehaviortree_cpp_v3.so
	linux-vdso.so.1 (0x00007ffefb3b5000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f4a1b422000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f4a1b41c000)
	libncurses.so.6 => /lib/x86_64-linux-gnu/libncurses.so.6 (0x00007f4a1b3f3000)
	libtinfo.so.6 => /lib/x86_64-linux-gnu/libtinfo.so.6 (0x00007f4a1b3c3000)
	libzmq.so.5 => /lib/x86_64-linux-gnu/libzmq.so.5 (0x00007f4a1b31d000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f4a1b139000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f4a1b11e000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4a1af2c000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f4a1b533000)
	libsodium.so.23 => /lib/x86_64-linux-gnu/libsodium.so.23 (0x00007f4a1aed4000)
	libpgm-5.2.so.0 => /lib/x86_64-linux-gnu/libpgm-5.2.so.0 (0x00007f4a1ae85000)
	libnorm.so.1 => /lib/x86_64-linux-gnu/libnorm.so.1 (0x00007f4a1ad2a000)
	libgssapi_krb5.so.2 => /lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007f4a1acdb000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4a1ab8c000)
	libkrb5.so.3 => /lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007f4a1aaaf000)
	libk5crypto.so.3 => /lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007f4a1aa7e000)
	libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007f4a1aa77000)
	libkrb5support.so.0 => /lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007f4a1aa66000)
	libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007f4a1aa5f000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f4a1aa43000)
```
dependency for .so library built without `libboost-context`
```
❯ ldd install/behaviortree_cpp_v3/lib/libbehaviortree_cpp_v3.so
	linux-vdso.so.1 (0x00007ffcf31a0000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fa8f40cb000)
	libncurses.so.6 => /lib/x86_64-linux-gnu/libncurses.so.6 (0x00007fa8f40a2000)
	libtinfo.so.6 => /lib/x86_64-linux-gnu/libtinfo.so.6 (0x00007fa8f4072000)
	libzmq.so.5 => /lib/x86_64-linux-gnu/libzmq.so.5 (0x00007fa8f3fcc000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fa8f3dea000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fa8f3dcd000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa8f3daa000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa8f3bb8000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fa8f41d0000)
	libsodium.so.23 => /lib/x86_64-linux-gnu/libsodium.so.23 (0x00007fa8f3b60000)
	libpgm-5.2.so.0 => /lib/x86_64-linux-gnu/libpgm-5.2.so.0 (0x00007fa8f3b11000)
	libnorm.so.1 => /lib/x86_64-linux-gnu/libnorm.so.1 (0x00007fa8f39b6000)
	libgssapi_krb5.so.2 => /lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007fa8f3967000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa8f3818000)
	libkrb5.so.3 => /lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007fa8f373b000)
	libk5crypto.so.3 => /lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007fa8f370a000)
	libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007fa8f3703000)
	libkrb5support.so.0 => /lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007fa8f36f2000)
	libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007fa8f36eb000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007fa8f36cf000)
```
dependency for .so library built after rosdep install
```
❯ ldd install/behaviortree_cpp_v3/lib/libbehaviortree_cpp_v3.so
	linux-vdso.so.1 (0x00007ffe60ffc000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f41d3a69000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f41d3a63000)
	libncurses.so.6 => /lib/x86_64-linux-gnu/libncurses.so.6 (0x00007f41d3a3a000)
	libtinfo.so.6 => /lib/x86_64-linux-gnu/libtinfo.so.6 (0x00007f41d3a0a000)
	libzmq.so.5 => /lib/x86_64-linux-gnu/libzmq.so.5 (0x00007f41d3964000)
	libboost_context.so.1.71.0 => /lib/x86_64-linux-gnu/libboost_context.so.1.71.0 (0x00007f41d395c000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f41d377a000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f41d375f000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f41d356d000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f41d3b8e000)
	libsodium.so.23 => /lib/x86_64-linux-gnu/libsodium.so.23 (0x00007f41d3515000)
	libpgm-5.2.so.0 => /lib/x86_64-linux-gnu/libpgm-5.2.so.0 (0x00007f41d34c6000)
	libnorm.so.1 => /lib/x86_64-linux-gnu/libnorm.so.1 (0x00007f41d3369000)
	libgssapi_krb5.so.2 => /lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007f41d331c000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f41d31cd000)
	libkrb5.so.3 => /lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007f41d30f0000)
	libk5crypto.so.3 => /lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007f41d30bf000)
	libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007f41d30b6000)
	libkrb5support.so.0 => /lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007f41d30a7000)
	libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007f41d30a0000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f41d3084000)
```

**Comment by wep21** [comment]
The apt library has a lack of boost dependecy, so this may fix this issue.

**Comment by facontidavide** [comment]
thanks

**Comment by wep21** [comment]
@facontidavide Could you create a new release for `galactic`, `rolling`?

**Pull request merged**
