### PR TITLE
Implement writeTreeDTD()

### PR DESCRIPTION
**Pull request by galou**
Add `<?xml-model href="tree.dtd" type="application/xml-dtd"?>`  or `<!DOCTYPE root SYSTEM "tree.dtd">` to use the benefits of DTD.

### CODE REVIEW

**Comment by galou** [comment]
I'm actually not sure whether `<include/>` is allowed within `<TreeNodesModel/>` or `<BehaviorTree/>`.

**Comment by galou** [comment]
What about `<SubTree/>` within `<TreeNodesModel/>`? If they are accepted, I have the issue that DTD is not powerful enough to describe differently a `<SubTree/>` within `<root/>` and within `<TreeNodesModel/>` (I don't know much about DTD).

**Comment by galou** [comment]
@facontidavide what is blocking merging?

**Comment by facontidavide** [comment]
Could you build an example showing how this works in the folder [examples](https://github.com/BehaviorTree/BehaviorTree.CPP/tree/master/examples)?
Something like **ex06_something_something.cpp**

> I'm actually not sure whether <include/> is allowed within <TreeNodesModel/> or <BehaviorTree/>

It is not

> What about <SubTree/> within <TreeNodesModel/>? If they are accepted, I have the issue that DTD is not powerful enough to describe differently a <SubTree/> within <root/> and within <TreeNodesModel/> (I don't know much about DTD).

It is now. Look at example [ex05_subtree_model](https://github.com/BehaviorTree/BehaviorTree.CPP/blob/master/examples/ex05_subtree_model.cpp)

**Pull request closed without merging**
