### PR TITLE
Remove unused lambda capture

### PR DESCRIPTION
**Pull request by rotu**
Make clang -Wunused-lambda-capture happy.

### CODE REVIEW

**Comment by rotu** [comment]
Not sure why the CI build is failing. Misconfiguration?

**Comment by facontidavide** [comment]
I will try to fix the CI today and merge the PR. Thanks

**Comment by rotu** [comment]
@facontidavide no luck?

**Comment by facontidavide** [comment]
I had no time to look into CI, but the change looks good to me

**Pull request merged**
