### PR TITLE
Issue #768: Add unit test to reproduce

### PR DESCRIPTION
**Pull request by KentaKato**
Unit test to reproduce issue https://github.com/BehaviorTree/BehaviorTree.CPP/issues/768

### CODE REVIEW

**Comment by facontidavide** [comment]
There are two errors in this test:

1. First in line 577, you should use `std::optional`, not `std::shared_ptr`
2. The following XML is wrong:

```xml
<NodeWithDefaultNullptr input=""/>
```

And should be instead:
```xml
<NodeWithDefaultNullptr />
```
In fact, the former version will override the default value and assigns to the port an **empty string**

**Comment by KentaKato** [comment]
@facontidavide 
Regarding point 2, I understand that to use the default value, the port should not be listed in the XML.

Yet, with Groot2, an empty string is automatically applied to any empty Port fields. Therefore, to ensure that default values are utilized for certain ports when generating a tree with Groot2, would it be accurate to say that the necessary steps are:

1. Outputting XML from Groot2
2. Removing the ports where default values are intended to be used

Is this understanding correct?

**Comment by facontidavide** [comment]
> Yet, with Groot2, an empty string is automatically applied to any empty Port fields

That is an entirely separate problem that I will be happy to fix. 
But I just check and that doesn' happen in Groot2 1.5.2

image

If the default value is specified in the **<TreeNodesModel>** than Groot2 does to add ports with empty strings.

Have a look at commit 6c9929c99e0546fcb51d9a0e2dc1febe5c7a624b , where I cherry-picked some of your code.

You will now be alerted that the default is overridden when the tree is constructed.

**Comment by KentaKato** [comment]
I deeply appreciate the verification and update.

I have understood the specifications of Groot2 version 1.5.2 and have also confirmed that alerts are generated.
Upon further verification, I identified the cause of the issue I was facing.

When generating XML, I have been outputting the TreeNodesModel to the console using BT::writeTreeNodesModelXML and then copying & pasting it into an XML file. It seems that BT::writeTreeNodesModelXML outputs default="" when the default value is not of a primitive type (such as nullptr or std::optional). As a result, it seems that an empty string "" was being assigned as the default value for empty Ports on Groot2.

In cases where a non-primitive type is set as the default value, what procedure is expected for generating the TreeNodesModel?

**Comment by facontidavide** [comment]
Oh, thanks for finding this.

I will have a look and see if I can fix it.

**Pull request closed without merging**
