### PR TITLE
Add the possibility to remove a blackboard entry.

### PR DESCRIPTION
**Pull request by galou**
Add a node to use this functionality.

### CODE REVIEW

**Comment by galou** [comment]
This is related to #706 . I need the ability to have "local" variables. Instead of variable scope, I can now delete some blackboard entries at the end of my subtree so that I have a clean blackboard in the case that the subtree is called again.

**Comment by facontidavide** [comment]
this looks useful. 
See my suggested change in the copyright. After that fix, I will merge it

**Review by facontidavide — CHANGES_REQUESTED** [review]

**Comment by facontidavide** [comment]
I was able to commit that myself. Merging as soon as Ci turns green

**Comment by corot** [comment]
Agree this looks useful. But wouldn't be neater to use SetBackboard with an empty input?
Would be that possible?
:thinking:

**Comment by facontidavide** [comment]
merged with some changes. Thanks

**Pull request merged**
